spring.datasource.url=jdbc:postgresql://localhost:5432/picture
spring.datasource.username=polin
spring.datasource.password=polin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
server.error.whitelabel.enabled=false
server.error.include-message=always
