
spring.datasource.url=jdbc:postgresql://localhost:5432/picture
spring.datasource.username=polin
spring.datasource.password=polin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.cors.allowed-origins=http://localhost:5173
server.port=9080
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
