
spring.datasource.url=jdbc:postgresql://localhost:5432/picture
spring.datasource.username=polin
spring.datasource.password=polin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8082
